INSERT INTO estetoscopios (nombre, descripcion, precio) VALUES
('LithoCare Basic', 'Estetoscopio de litio ligero para uso general.', 24.95),
('LithoCare Plus', 'Estetoscopio de litio con membrana de alta sensibilidad.', 32.50),
('LithoCare Pro', 'Modelo profesional fabricado con aleación ligera de litio.', 58.90),
('LithoSound 100', 'Estetoscopio compacto para estudiantes de medicina.', 19.99),
('LithoSound 200', 'Modelo de litio con aislamiento acústico mejorado.', 29.95),
('LithoSound 300', 'Estetoscopio de doble campana para diagnóstico general.', 39.90),
('LithoSound 400', 'Estetoscopio profesional con tubo flexible reforzado.', 49.50),
('LithoSound 500', 'Modelo avanzado con excelente respuesta acústica.', 69.95),
('CardioLith Basic', 'Estetoscopio de litio orientado a exploraciones cardíacas.', 45.90),
('CardioLith Pro', 'Modelo cardiológico profesional de alta sensibilidad.', 79.90),
('CardioLith Max', 'Estetoscopio cardiológico premium fabricado en litio.', 94.50),
('MediLith One', 'Estetoscopio ligero para consultas médicas generales.', 22.90),
('MediLith Two', 'Modelo ergonómico con auriculares ajustables.', 27.50),
('MediLith Three', 'Estetoscopio con campana reversible y estructura de litio.', 34.90),
('MediLith Four', 'Modelo profesional con membrana de doble frecuencia.', 54.95),
('MediLith Five', 'Estetoscopio avanzado para diagnóstico clínico.', 74.90),
('Lithium Pulse', 'Estetoscopio ligero especializado en auscultación cardíaca.', 63.50),
('Lithium Pulse Mini', 'Versión compacta para estudiantes y enfermería.', 26.95),
('Lithium Pulse Pro', 'Modelo profesional con alta precisión acústica.', 82.90),
('Lithium Pulse X', 'Estetoscopio premium de litio con diseño ergonómico.', 96.50),
('SonoLith Basic', 'Estetoscopio sencillo y resistente para uso cotidiano.', 21.50),
('SonoLith Classic', 'Diseño clásico fabricado con componentes ligeros de litio.', 28.90),
('SonoLith Advance', 'Modelo avanzado con excelente aislamiento acústico.', 51.90),
('SonoLith Cardio', 'Estetoscopio especializado en auscultación cardiovascular.', 77.50),
('SonoLith Pediatric', 'Modelo de litio diseñado para pacientes pediátricos.', 42.90),
('SonoLith Neonatal', 'Estetoscopio compacto para exploración neonatal.', 46.50),
('LithMed Student', 'Modelo económico pensado para estudiantes sanitarios.', 18.95),
('LithMed Nurse', 'Estetoscopio ligero para profesionales de enfermería.', 25.90),
('LithMed Doctor', 'Modelo profesional para medicina general.', 48.95),
('LithMed Cardio', 'Estetoscopio especializado en cardiología.', 84.90),
('LithMed Elite', 'Modelo premium con acabado de litio pulido.', 97.90),
('AuriLith 10', 'Estetoscopio básico con auriculares cómodos.', 23.50),
('AuriLith 20', 'Modelo ligero con membrana acústica mejorada.', 31.90),
('AuriLith 30', 'Estetoscopio profesional con doble campana.', 43.50),
('AuriLith 40', 'Modelo avanzado con tubo de alta resistencia.', 56.90),
('AuriLith 50', 'Estetoscopio premium con excelente aislamiento sonoro.', 73.50),
('ClinLith Start', 'Estetoscopio de iniciación para prácticas clínicas.', 17.90),
('ClinLith Standard', 'Modelo estándar para centros médicos y consultas.', 33.95),
('ClinLith Expert', 'Estetoscopio profesional de alta sensibilidad.', 61.90),
('ClinLith Ultra', 'Modelo avanzado para diagnóstico especializado.', 88.50),
('NeoLith Baby', 'Estetoscopio pequeño diseñado para neonatología.', 39.95),
('NeoLith Kids', 'Modelo pediátrico ligero con campana reducida.', 41.50),
('NeoLith Pro', 'Estetoscopio profesional para pediatría y neonatología.', 68.90),
('DoctorLith S1', 'Modelo básico para exploraciones médicas rutinarias.', 27.95),
('DoctorLith S2', 'Estetoscopio de litio con buena respuesta acústica.', 36.90),
('DoctorLith S3', 'Modelo profesional con diseño ergonómico.', 52.50),
('DoctorLith S4', 'Estetoscopio avanzado con membrana multifrecuencia.', 71.90),
('DoctorLith S5', 'Modelo de gama alta para especialistas.', 91.50),
('LithScope Prime', 'Estetoscopio profesional ligero y resistente.', 64.95),
('LithScope Ultimate', 'Estetoscopio premium de litio para diagnóstico avanzado.', 98.90);