INSERT INTO facultativos (nombre, apellidos, email, n_colegiado) VALUES
('Laura', 'Martínez García', 'laura.martinez@example.com', 'CV-PSI-1001'),
('Carlos', 'Sánchez López', 'carlos.sanchez@example.com', 'CV-PSI-1002'),
('Marta', 'Navarro Ruiz', 'marta.navarro@example.com', 'CV-PSI-1003'),
('David', 'Torres Romero', 'david.torres@example.com', 'CV-PSI-1004'),
('Ana', 'Gómez Ferrer', 'ana.gomez@example.com', 'CV-PSI-1005'),
('Javier', 'Moreno Vidal', 'javier.moreno@example.com', 'CV-PSI-1006'),
('Elena', 'Pérez Molina', 'elena.perez@example.com', 'CV-PSI-1007'),
('Sergio', 'Ortega Campos', 'sergio.ortega@example.com', 'CV-PSI-1008'),
('Lucía', 'Ramos Pastor', 'lucia.ramos@example.com', 'CV-PSI-1009'),
('Miguel', 'Domínguez Gil', 'miguel.dominguez@example.com', 'CV-PSI-1010'),

('Paula', 'Serrano Ibáñez', 'paula.serrano@example.com', 'CV-PSI-1011'),
('Alejandro', 'Vega Castillo', 'alejandro.vega@example.com', 'CV-PSI-1012'),
('Cristina', 'Molina Esteve', 'cristina.molina@example.com', 'CV-PSI-1013'),
('Rubén', 'Ferrer Soler', 'ruben.ferrer@example.com', 'CV-PSI-1014'),
('Natalia', 'Giménez Pascual', 'natalia.gimenez@example.com', 'CV-PSI-1015'),
('Álvaro', 'Blasco Peris', 'alvaro.blasco@example.com', 'CV-PSI-1016'),
('Sara', 'Calatayud Mora', 'sara.calatayud@example.com', 'CV-PSI-1017'),
('Pablo', 'Llorens Martí', 'pablo.llorens@example.com', 'CV-PSI-1018'),
('Beatriz', 'Soriano Segura', 'beatriz.soriano@example.com', 'CV-PSI-1019'),
('Daniel', 'Cervera Costa', 'daniel.cervera@example.com', 'CV-PSI-1020'),

('Irene', 'Valero Gimeno', 'irene.valero@example.com', 'CV-PSI-1021'),
('Adrián', 'Ballester Roig', 'adrian.ballester@example.com', 'CV-PSI-1022'),
('Silvia', 'Benavent Miralles', 'silvia.benavent@example.com', 'CV-PSI-1023'),
('Víctor', 'Carbonell Pons', 'victor.carbonell@example.com', 'CV-PSI-1024'),
('Claudia', 'Beltrán Sanchis', 'claudia.beltran@example.com', 'CV-PSI-1025'),
('Marcos', 'Montesinos Roca', 'marcos.montesinos@example.com', 'CV-PSI-1026'),
('Patricia', 'Escribano Ferrando', 'patricia.escribano@example.com', 'CV-PSI-1027'),
('Héctor', 'Puig Salvador', 'hector.puig@example.com', 'CV-PSI-1028'),
('Noelia', 'Marco Aparicio', 'noelia.marco@example.com', 'CV-PSI-1029'),
('Raúl', 'Galiana Bosch', 'raul.galiana@example.com', 'CV-PSI-1030'),

('Andrea', 'Fuster Lloret', 'andrea.fuster@example.com', 'CV-PSI-1031'),
('Óscar', 'Redondo Estevan', 'oscar.redondo@example.com', 'CV-PSI-1032'),
('Marina', 'Cortés Albiol', 'marina.cortes@example.com', 'CV-PSI-1033'),
('Iván', 'Ribera Mateu', 'ivan.ribera@example.com', 'CV-PSI-1034'),
('Alicia', 'Pardo Belda', 'alicia.pardo@example.com', 'CV-PSI-1035'),
('Gonzalo', 'Aguilar Sendra', 'gonzalo.aguilar@example.com', 'CV-PSI-1036'),
('Nuria', 'Vicente Lozano', 'nuria.vicente@example.com', 'CV-PSI-1037'),
('Fernando', 'Requena Fabra', 'fernando.requena@example.com', 'CV-PSI-1038'),
('Eva', 'Climent Ferri', 'eva.climent@example.com', 'CV-PSI-1039'),
('Jorge', 'Alonso Miró', 'jorge.alonso@example.com', 'CV-PSI-1040'); 