INSERT INTO calzados (nombre, descripcion, precio) VALUES
('Urban Step', 'Zapatilla urbana ligera de color negro', 49.95),
('Runner Pro', 'Zapatilla deportiva para running', 69.90),
('Classic Walk', 'Zapato clásico de piel sintética', 59.95),
('Mountain Trek', 'Bota de montaña resistente al agua', 89.90),
('Summer Sand', 'Sandalia ligera para verano', 29.95),
('City Sneaker', 'Zapatilla casual para uso diario', 44.90),
('Elegant Black', 'Zapato elegante negro para vestir', 74.95),
('Sport Flex', 'Zapatilla deportiva flexible', 54.90),
('Trail Master', 'Zapatilla preparada para senderismo', 79.95),
('Beach Walk', 'Chancla cómoda para playa y piscina', 19.90),

('Retro Runner', 'Zapatilla deportiva de estilo retro', 64.95),
('Office Brown', 'Zapato marrón para oficina', 69.95),
('Winter Boot', 'Bota cálida para los meses de invierno', 84.90),
('Canvas Blue', 'Zapatilla de lona azul', 34.95),
('Street White', 'Zapatilla urbana blanca', 49.90),
('Comfort Plus', 'Zapato cómodo para largas caminatas', 59.90),
('Sport Air', 'Zapatilla deportiva con cámara de aire', 79.90),
('Hiking Pro', 'Bota técnica para senderismo', 94.95),
('Casual Grey', 'Zapatilla casual de color gris', 44.95),
('Elegant Brown', 'Zapato elegante marrón', 72.90),

('Running Light', 'Zapatilla ultraligera para correr', 74.95),
('Urban Red', 'Zapatilla urbana de color rojo', 46.90),
('Trekking Green', 'Bota de trekking verde', 86.95),
('Classic Oxford', 'Zapato clásico estilo Oxford', 78.90),
('Summer Beach', 'Sandalia abierta para verano', 27.95),
('Fitness Move', 'Zapatilla para gimnasio y fitness', 57.90),
('Daily Comfort', 'Calzado cómodo para uso diario', 52.95),
('Street High', 'Zapatilla urbana de caña alta', 61.90),
('Trail Rock', 'Calzado resistente para terrenos rocosos', 88.95),
('Soft Moccasin', 'Mocasín ligero y flexible', 64.90),

('Urban Canvas', 'Zapatilla urbana fabricada en lona', 39.95),
('Running Speed', 'Zapatilla diseñada para entrenamientos rápidos', 82.90),
('Business Black', 'Zapato negro para traje y oficina', 76.95),
('Mountain Peak', 'Bota de montaña con suela reforzada', 92.90),
('Casual Navy', 'Zapatilla casual azul marino', 47.95),
('Sport Energy', 'Zapatilla deportiva para entrenamiento', 67.90),
('Summer Comfort', 'Sandalia acolchada para verano', 32.95),
('Winter Trek', 'Bota de invierno para exteriores', 89.95),
('Street Classic', 'Zapatilla urbana de diseño clásico', 51.90),
('Running Cloud', 'Zapatilla de running con alta amortiguación', 84.95),

('Urban Night', 'Zapatilla negra de estilo moderno', 55.90),
('Hiking Adventure', 'Bota para rutas y excursiones', 91.95),
('Casual Beige', 'Zapatilla casual de color beige', 45.90),
('Sport Dynamic', 'Zapatilla deportiva dinámica y ligera', 62.95),
('Classic Derby', 'Zapato clásico estilo Derby', 73.90),
('Beach Flip', 'Chancla ligera y resistente al agua', 17.95),
('Fitness Power', 'Zapatilla para entrenamiento intensivo', 71.90),
('Urban Minimal', 'Zapatilla urbana de diseño minimalista', 53.95),
('Trail Explorer', 'Zapatilla todoterreno para rutas', 87.90),
('Premium Walk', 'Zapato cómodo con acabado premium', 81.95);